[platformio]
default_envs = sunnyTV


[env:sunnyESP_v03]
board = sunnyESP_v03
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags}  ${esp32_idf_V4.build_flags} -D WLED_RELEASE_NAME='"ESP32_V4_sunny"' -D WLED_AP_SSID='"sunnyESP"' -D WLED_DISABLE_ALEXA -D WLED_DISABLE_HUESYNC -D USERMOD_PWM_OUTPUTS -D LED_TYPES=30 #30=SK6812 #-D WLED_DISABLE_BROWNOUT_DET
  ${esp32.AR_build_flags}
 -D WLED_DEBUG
lib_deps = ${esp32_idf_V4.lib_deps}
  ${esp32.AR_lib_deps}
;monitor_filters = esp32_exception_decoder
board_build.partitions = default_16MB.csv
board_build.flash_mode = qio
upload_speed = 921600
monitor_speed = 115200

[env:sunnyFogmachine]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags}  ${esp32_idf_V4.build_flags} -D WLED_RELEASE_NAME='"ESP32_V4_sunnyFogmachine"' -D WLED_AP_SSID='"sunnyESP_fog"' -D WLED_DISABLE_ALEXA -D WLED_DISABLE_HUESYNC -D USERMOD_PWM_OUTPUTS -D LED_TYPES=40 -D PIXEL_COUNTS=1   #40=onoff
  ${esp32.AR_build_flags}
 -D WLED_DEBUG
lib_deps = ${esp32_idf_V4.lib_deps}
  ${esp32.AR_lib_deps}
monitor_filters = esp32_exception_decoder
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = qio
upload_speed = 921600
monitor_speed = 115200

[env:sunnyTV]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags}  ${esp32_idf_V4.build_flags} -D WLED_RELEASE_NAME='"ESP32_V4_sunnyTV"' -D WLED_AP_SSID='"sunnyESP_tv"' -D WLED_DISABLE_ALEXA -D WLED_DISABLE_HUESYNC -D USERMOD_PWM_OUTPUTS -D LED_TYPES=40 -D PIXEL_COUNTS=1
  ${esp32.AR_build_flags}
 -D WLED_DEBUG
lib_deps = ${esp32_idf_V4.lib_deps}
  ${esp32.AR_lib_deps}
monitor_filters = esp32_exception_decoder
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = qio
upload_speed = 921600
monitor_speed = 115200
